# Generated by Django 5.1.7 on 2025-04-19 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congestionprediction',
            name='actual_congestion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='congestionprediction',
            name='error_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='congestionprediction',
            name='is_bottleneck_affected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='congestionprediction',
            name='prediction_confidence',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='confidence_score',
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='current_speed',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='free_flow_speed',
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='is_bottleneck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='road_type',
            field=models.CharField(choices=[('FRC0', 'Highway (NH5)'), ('FRC1', 'Major Road (Ferozepur Rd)'), ('FRC2', 'Secondary Road'), ('FRC3', 'Local Road'), ('FRC4', 'Ramp/Exit Road'), ('FRC5', 'Alley/Private Road'), ('FRC6', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='congestion_level',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('light', 'Light'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='location',
            field=models.CharField(default='Ludhiana', max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AddIndex(
            model_name='trafficdata',
            index=models.Index(fields=['timestamp', 'latitude', 'longitude'], name='app_traffic_timesta_eb5000_idx'),
        ),
        migrations.AddConstraint(
            model_name='trafficdata',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude', 'timestamp'), name='unique_location_time'),
        ),
    ]
