# Generated by Django 5.2.14 on 2026-05-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_congestionprediction_actual_congestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid_latitude', models.FloatField()),
                ('centroid_longitude', models.FloatField()),
                ('radius_meters', models.FloatField(default=35.0)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('confidence_aggregate', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='potholereport',
            name='accelerometer_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potholereport',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='potholereport',
            name='source_device_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='potholereport',
            name='source_type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='potholereport',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='app.potholecluster'),
        ),
        migrations.CreateModel(
            name='SensorDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accelerometer_z', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
