# Generated by Django 5.2.14 on 2026-05-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_spatial_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_read_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='potholecluster',
            name='cluster_geo_idx',
        ),
        migrations.RemoveIndex(
            model_name='potholecluster',
            name='cluster_verified_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='potholereport',
            name='pothole_geo_idx',
        ),
        migrations.RemoveIndex(
            model_name='potholereport',
            name='pothole_device_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensordatapoint',
            name='sensor_device_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='userlocation',
            name='user_location_geo_idx',
        ),
    ]
